# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Sapin
site_url: https://sbntt.github.io/Sapin_docs/
repo_url: https://github.com/SBNTT/Sapin
nav:
  - Home: index.md
  - Docs:
      - Introduction: introduction.md
      - Installation: installation.md
      - Usage: usage.md
      - Template syntax:
          - Interpolation: template_syntax/interpolation.md
          - Computed attributes: template_syntax/computed_attributes.md
          - Conditional rendering: template_syntax/conditional_rendering.md
          - Loops: template_syntax/loops.md
          - Fragments: template_syntax/fragments.md
          - Composition: template_syntax/composition.md
          - Slots: template_syntax/slots.md
      - Lifecycle hooks: lifecycle_hooks.md
      - Component linting: component_linting.md
      - Interop: interop.md
      - Examples: examples.md
      - Roadmap: roadmap.md
theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - content.code.copy
  custom_dir: docs/overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Emojis & icons
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences