<?php

namespace Sapin\Engine\Test\Integration\Else;

use Sapin\Engine\Component;

final class ElseTestComponent extends Component
{
    public function __construct(
            public int $a,
            public int $b,
    )
    {
    }
} ?>

<template>
    <fragment :if="$this->a === $this->b">
        a is the same as b!
    </fragment>
    <fragment :else>
        a is not the same as b!
    </fragment>
</template>
