<?php

namespace Sapin\Engine\Test\Integration\ForEachLoop;

use Sapin\Engine\Component;

final class ForEachLoopTestComponentB extends Component
{
    /**
     * @param int[] $numbers
     */
    public function __construct(
            public readonly array $numbers,
    )
    {
    }
} ?>

<template>
    <ul>
        <li :foreach="$this->numbers as $number" :if="$number % 2 === 0">
            {{ $number }}
        </li>
    </ul>
</template>
