<?php

namespace Sapin\Engine\Test\Integration\ForEachLoop;

use Sapin\Engine\Component;

final class ForEachLoopTestComponentA extends Component
{
    /**
     * @param string[] $fruits
     */
    public function __construct(
            public readonly array $fruits,
    )
    {
    }
} ?>

<template>
    <ul>
        <li :foreach="$this->fruits as $fruit">
            {{ $fruit }}
        </li>
    </ul>
</template>
